// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image3":
            case "myImage1":return img`
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffeeeee.................................................fffff
fffffeeeee.................................................fffff
fffffeeeee.................................................fffff
fffffeeeee.................................................fffff
fffffeeeee.................................................fffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
`;
            case "image1":
            case "myImage":return img`
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffff575757575757575757575757575757575757575757575757575757fffff
fffff777577757775777577757775777577757775777577757775777577fffff
fffff777777777777777777777777777777777777777777777777777777fffff
fffff777577757775777577757775777577757775777577757775777577fffff
fffff575757575757575757575757575757575757575757575757575757fffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
`;
            case "image4":
            case "myImage2":return img`
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffeeeeeeeeee............................................fffff
fffffeeeeeeeeee............................................fffff
fffffeeeeeeeeee............................................fffff
fffffeeeeeeeeee............................................fffff
fffffeeeeeeeeee............................................fffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
`;
            case "image2":
            case "myImage0":return img`
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffff222222222222222.......................................fffff
fffff222222222222222.......................................fffff
fffff222222222222222.......................................fffff
fffff222222222222222.......................................fffff
fffff222222222222222.......................................fffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
`;
            case "image5":
            case "myImage3":return img`
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffff22222222222222222222..................................fffff
fffff22222222222222222222..................................fffff
fffff22222222222222222222..................................fffff
fffff22222222222222222222..................................fffff
fffff22222222222222222222..................................fffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
`;
            case "image6":
            case "myImage4":return img`
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffff4444444444444444444444444.............................fffff
fffff4444444444444444444444444.............................fffff
fffff4444444444444444444444444.............................fffff
fffff4444444444444444444444444.............................fffff
fffff4444444444444444444444444.............................fffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
`;
            case "image7":
            case "myImage5":return img`
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffff444444444444444444444444444444........................fffff
fffff444444444444444444444444444444........................fffff
fffff444444444444444444444444444444........................fffff
fffff444444444444444444444444444444........................fffff
fffff444444444444444444444444444444........................fffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
`;
            case "image8":
            case "myImage6":return img`
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffff55555555555555555555555555555555555...................fffff
fffff55555555555555555555555555555555555...................fffff
fffff55555555555555555555555555555555555...................fffff
fffff55555555555555555555555555555555555...................fffff
fffff55555555555555555555555555555555555...................fffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
`;
            case "image9":
            case "myImage7":return img`
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffff5555555555555555555555555555555555555555..............fffff
fffff5555555555555555555555555555555555555555..............fffff
fffff5555555555555555555555555555555555555555..............fffff
fffff5555555555555555555555555555555555555555..............fffff
fffff5555555555555555555555555555555555555555..............fffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
`;
            case "image10":
            case "myImage8":return img`
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffff777777777777777777777777777777777777777777777.........fffff
fffff777777777777777777777777777777777777777777777.........fffff
fffff777777777777777777777777777777777777777777777.........fffff
fffff777777777777777777777777777777777777777777777.........fffff
fffff777777777777777777777777777777777777777777777.........fffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
`;
            case "image11":
            case "myImage9":return img`
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffff77777777777777777777777777777777777777777777777777....fffff
fffff77777777777777777777777777777777777777777777777777....fffff
fffff77777777777777777777777777777777777777777777777777....fffff
fffff77777777777777777777777777777777777777777777777777....fffff
fffff77777777777777777777777777777777777777777777777777....fffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
`;
            case "image12":
            case "myImage10":return img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`;
            case "image13":
            case "myImage11":return img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . f f . . . . . . . 
. f f f . f f 1 1 f f . f f f . 
f 9 9 9 f 1 1 8 8 1 1 f 9 9 9 f 
. f f f 1 1 8 9 9 8 1 1 f f f . 
. . . . f 1 1 1 1 1 1 f . . . . 
. . . . . f 1 f f 1 f . . . . . 
. . . . . . f . . f . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`;
            case "image15":
            case "myImage13":return img`
. . . . . . . . . . . . . . . . 
. f f . . . . . . . . . . . . . 
. f 9 f . . . . . . . . . . . . 
. . f 9 f f . . . . . . . . . . 
. . . f 9 1 f f f . . . . . . . 
. . . f 1 1 1 1 1 f . . . . . . 
. . . f 1 1 8 8 1 1 f . . . . . 
. . . f 1 1 9 9 8 1 f . . . . . 
. . . f 1 1 1 9 8 1 f . . . . . 
. . f 1 f f 1 1 1 1 1 f . . . . 
. . f f . f 1 1 1 1 9 f . . . . 
. . . . f 1 f f f f f 9 f . . . 
. . . . f f . . . . . f 9 f . . 
. . . . . . . . . . . . f f . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`;
            case "image14":
            case "myImage12":return img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . f f . 
. . . . . . . . . . . . f 9 f . 
. . . . . . . . . . f f 9 f . . 
. . . . . . . f f f 1 9 f . . . 
. . . . . . f 1 1 1 1 1 f . . . 
. . . . . f 1 1 8 8 1 1 f . . . 
. . . . . f 1 8 9 9 1 1 f . . . 
. . . . . f 1 8 9 1 1 1 f . . . 
. . . . f 1 1 1 1 1 f f 1 f . . 
. . . . f 9 1 1 1 1 f . f f . . 
. . . f 9 f f f f f 1 f . . . . 
. . f 9 f . . . . . f f . . . . 
. . f f . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`;
            case "image16":
            case "myImage14":return img`
. . . . . f f f . . . . . . . . 
. . . . f e e e f . . . . . . . 
. . . . . f e e e f . f f f . . 
. . . . . . f e e e f e 1 f . . 
. . . . . . . f e e e e 5 5 f . 
. . . . . . . f e e e e e f . . 
. . . . . . f e e e e e f . . . 
. . . . . . f e e e e e f . . . 
. . . . . . . f f e f e f . . . 
. . . . . . . . . f . f . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

    helpers._registerFactory("song", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
